#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server
grep "localhost" /etc/hosts > /dev/null
# if [ $ex -eq 0 ]
# then
sed -i '/localhost/c\127.0.0.2 localhost' /etc/hosts
# else
    # echo "127.0.0.2 localhost" >> /etc/hosts
# fi
echo "8.8.8.8 facebook.com" >> /etc/hosts